name: Build Push and Deploy

on:
  push:
    branches:
      - main

jobs:

  build-push-deploy:

    runs-on: self-hosted

    steps:

      # 1. Checkout source code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Add Docker Desktop to PATH
      - name: Add Docker to PATH
        shell: powershell
        run: |
          $dockerPath = "C:\Users\BoggalaSaiJayaram\AppData\Local\Programs\DockerDesktop\resources\bin"
          Write-Host "Adding Docker path: $dockerPath"
          Add-Content -Path $env:GITHUB_PATH -Value $dockerPath

      # 3. Verify Docker
      - name: Verify Docker
        shell: powershell
        run: |
          Write-Host "Docker location:"
          where.exe docker

          Write-Host "Docker version:"
          docker version

      # 4. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build Docker image
      - name: Build Docker image
        shell: powershell
        run: |
          docker build -t jai842/sample-app:latest .

      # 6. Push Docker image to Docker Hub
      - name: Push Docker image
        shell: powershell
        run: |
          docker push jai842/sample-app:latest

      # 7. Deploy application to Docker Desktop Kubernetes
      - name: Deploy to Kubernetes
        shell: powershell
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # 8. Restart deployment to pull the latest image
      - name: Restart Kubernetes deployment
        shell: powershell
        run: |
          kubectl rollout restart deployment/sample-app

      # 9. Wait for deployment
      - name: Wait for deployment
        shell: powershell
        run: |
          kubectl rollout status deployment/sample-app

      # 10. Check Kubernetes resources
      - name: Check Kubernetes
        shell: powershell
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl get services